"""Run full factory pipeline and write markdown report."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np

from ..active_learning.loop import ActiveLearningLoop
from ..eval.harness import evaluate_rag
from ..extraction.hybrid import HybridExtractor
from ..extraction.metrics import extraction_report
from ..feedback_ope.ips import ope_report
from ..feedback_ope.logging_policy import ReviewLogger
from ..rag.chunking import chunk_documents
from ..rag.retrieve import Retriever
from ..synthetic.corpus import PRIMARY_FIELDS, corpus_stats, generate_corpus


def run_factory(
    *,
    n_docs: int = 300,
    seed: int = 42,
    artifacts_dir: str | Path = "artifacts",
) -> dict[str, Any]:
    artifacts_dir = Path(artifacts_dir)
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)

    # --- corpus ---
    docs = generate_corpus(n_docs, seed=seed, char_error_rate=0.045)
    stats = corpus_stats(docs)

    # split
    idx = rng.permutation(len(docs))
    n_test = max(40, len(docs) // 5)
    n_train = len(docs) - n_test
    train = [docs[int(i)] for i in idx[:n_train]]
    test = [docs[int(i)] for i in idx[n_train:]]

    # --- Case A: extraction lift (rules vs hybrid) ---
    rules_preds = []
    ext_rules = HybridExtractor(seed=seed)
    for d in test:
        rules_preds.append(ext_rules.rule_extract(d.text, d.doc_type))
    fields = sorted({k for d in test for k in PRIMARY_FIELDS[d.doc_type]})
    golds = [d.fields for d in test]
    rules_metrics = extraction_report(rules_preds, golds, fields)

    hybrid = HybridExtractor(seed=seed).fit(train)
    hybrid_preds_raw = hybrid.predict(test)
    hybrid_preds = [{k: v for k, v in p.items() if not k.startswith("_")} for p in hybrid_preds_raw]
    hybrid_metrics = extraction_report(hybrid_preds, golds, fields)

    case_a = {
        "rules": rules_metrics,
        "hybrid": hybrid_metrics,
        "f1_lift": hybrid_metrics["micro"]["f1"] - rules_metrics["micro"]["f1"],
    }

    # --- Case B: RAG eval ---
    chunks = chunk_documents(docs, size=160, overlap=30)
    retriever = Retriever().index(chunks)
    rag_result = evaluate_rag(retriever, docs, seed=seed, n_per_type=12, k=5)
    case_b = {
        "n_chunks": len(chunks),
        "faithfulness": rag_result.faithfulness,
        "groundedness": rag_result.groundedness,
        "answer_relevance": rag_result.answer_relevance,
        "hit_at_5": rag_result.hit_at_5,
        "mrr": rag_result.mrr,
        "n_qa": rag_result.n,
    }

    # --- Case C: AL budget curve + OPE ---
    al = ActiveLearningLoop(
        train,
        test,
        seed=seed,
        seed_size=min(24, len(train) // 4),
        batch_size=12,
        budget=min(96, max(36, len(train) // 3)),
    )
    curve = al.run()
    case_c_al = ActiveLearningLoop.curve_to_dicts(curve)

    logger = ReviewLogger(hybrid, temperature=1.2, seed=seed)
    decisions = logger.log(test)
    case_c_ope = ope_report(decisions, threshold=0.4)

    results = {
        "corpus": stats,
        "case_a_extraction": case_a,
        "case_b_rag": case_b,
        "case_c_active_learning": case_c_al,
        "case_c_ope": case_c_ope,
        "n_train": len(train),
        "n_test": len(test),
        "seed": seed,
    }

    # persist json + md
    (artifacts_dir / "factory_results.json").write_text(json.dumps(results, indent=2), encoding="utf-8")
    write_report(results, artifacts_dir / "factory_report.md")
    return results


def write_report(results: dict[str, Any], path: str | Path) -> None:
    path = Path(path)
    a = results["case_a_extraction"]
    b = results["case_b_rag"]
    al = results["case_c_active_learning"]
    ope = results["case_c_ope"]
    corp = results["corpus"]

    al_rows = "\n".join(
        f"| {p['labeled']} | {p['f1_uncertainty']:.3f} | {p['f1_random']:.3f} |" for p in al
    )

    md = f"""# Document Intelligence Factory Report

Generated by `doc-intel-factory` (seed={results['seed']}).

## Corpus

- **N documents**: {corp['n']} (train={results['n_train']}, test={results['n_test']})
- **By type**: {corp['by_type']}
- **By layout**: {corp['by_layout']}
- **Mean chars / spans**: {corp['mean_chars']:.1f} / {corp['mean_spans']:.2f}

## Case A — Extraction lift (rules vs hybrid)

| System | Precision | Recall | F1 |
|--------|-----------|--------|-----|
| Rules only | {a['rules']['micro']['precision']:.3f} | {a['rules']['micro']['recall']:.3f} | {a['rules']['micro']['f1']:.3f} |
| Hybrid (rules+ML) | {a['hybrid']['micro']['precision']:.3f} | {a['hybrid']['micro']['recall']:.3f} | {a['hybrid']['micro']['f1']:.3f} |

**F1 lift (hybrid − rules)**: **{a['f1_lift']:.3f}**

### Per-field (hybrid)

| Field | P | R | F1 |
|-------|---|---|-----|
"""
    for name, m in a["hybrid"]["per_field"].items():
        md += f"| {name} | {m['precision']:.3f} | {m['recall']:.3f} | {m['f1']:.3f} |\n"

    md += f"""
## Case B — RAG evaluation (faithfulness / relevance / groundedness)

| Metric | Value |
|--------|-------|
| QA pairs | {b['n_qa']} |
| Chunks indexed | {b['n_chunks']} |
| Faithfulness | {b['faithfulness']:.3f} |
| Groundedness | {b['groundedness']:.3f} |
| Answer relevance | {b['answer_relevance']:.3f} |
| Hit@5 | {b['hit_at_5']:.3f} |
| MRR | {b['mrr']:.3f} |

Answers are **template-grounded** on retrieved spans (no hosted LLM).

## Case C — Active learning budget curve

| Labeled | F1 (uncertainty) | F1 (random) |
|---------|------------------|-------------|
{al_rows}

## Case C — Feedback OPE (review routing)

Logged review rate: {ope['review_rate_logged']:.3f}  
Target threshold: {ope['threshold']}

| Estimator | Estimate | |error| vs oracle |
|-----------|----------|---------------------|
| IPS | {ope['ips']['estimate']:.4f} | {ope['ips_abs_error']:.4f} |
| SNIPS | {ope['snips']['estimate']:.4f} | {ope['snips_abs_error']:.4f} |
| Naive | {ope['naive']['estimate']:.4f} | {ope['naive_abs_error']:.4f} |
| Oracle target value | {ope['oracle_target_value']:.4f} | 0 |

IPS ESS: {ope['ips']['ess']:.1f} | SNIPS ESS: {ope['snips']['ess']:.1f}

## Threats to validity

- Synthetic OCR noise ≠ production OCR engines or scanned PDFs.
- Template answers inflate faithfulness relative to free-form LLMs.
- OPE rewards are oracle-simulated; real human review costs/quality differ.
- TF-IDF retrieval is a baseline, not dense multilingual embeddings.

## What this is NOT

- Not production OCR / layout parsing (no Tesseract, no LayoutLM).
- Not a hosted LLM API wrapper.
- Not a claim of SOTA IE/RAG numbers — it is a **coherent systems lab**.
"""
    path.write_text(md, encoding="utf-8")
